### PR TITLE
add latex support

### PR DESCRIPTION
**Pull request by czhang03**
Inspired by https://github.com/James-Yu/LaTeX-Workshop/issues/387

This pull request will not be possible without the following resources:
- https://github.com/ojsheikh/unicode-latex/blob/master/src/latex.ts
- http://milde.users.sourceforge.net/LUCR/Math/unimathsymbols.pdf
- https://www.johndcook.com/blog/greek_letters/

### CODE REVIEW

**Comment by siegebell** [comment]
Thanks!

**Comment by czhang03** [comment]
hum... So this is not good?

**Comment by siegebell** [comment]
Oh. No, it means my github skills are no good. One moment...

**Comment by czhang03** [comment]
Hahaha, thanks dude.

**Comment by czhang03** [comment]
I will keep adding more stuff during the summer, hopefully.

**Comment by siegebell** [comment]
Hmm... But symbols ⯆, ⯅, and ⮚ are not supported by vscode's default fonts (on Windows) :(

Can you suggest alternatives? Otherwise I better remove them.

**Comment by czhang03** [comment]
I think I am using consolas font and they work fine. I am also on windows. I will try to check that out tomorrow.
Thank you for pointing that out.

**Comment by czhang03** [comment]
Unfortunately I cannot reproduce the issue you have.

My vscode version:
```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:38:45.278Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

My config file:
```json
// Place your settings in this file to overwrite the default settings
{
  "files.autoSave": "onFocusChange",

  "powershell.codeFormatting.openBraceOnSameLine": false,
  "editor.tabSize": 2,
  "git.confirmSync": false,
  "git.enableSmartCommit": true,

  // Latex
  // setup the build tool
  "latex-workshop.latex.tools": [
    {
      "command": "latexmk",
      "args": [
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        "-lualatex",
        "-auxdir=./aux_file/",
        "main.tex"
      ],
      "name": "Step 1: latexmk"
    }
  ],
  "latex-workshop.latex.recipes": [
    {
      "name": "toolchain",
      "tools": [
        "Step 1: latexmk"
      ]
    }
  ],
  // enable the checker
  "latex-workshop.chktex.enabled": true,
  // set the viewer
  "latex-workshop.view.pdf.viewer": "tab",
  "latex-workshop.view.pdf.external.command": {
    "command": "SumatraPDF.exe",
    "args": [
      "-inverse-search",
      "code.cmd -g %f:%l",
      "%PDF%",
    ]
  },
  // do not build on save
  // annoying when writing large document
  "latex-workshop.latex.autoBuild.onSave.enabled": false,



  //spell checker
  "spellright.notificationClass": "information",

  "git.autofetch": true

}
```
which is not related to font.

My font setting:
```json
  // Controls the font family.
  "editor.fontFamily": "Consolas, 'Courier New', monospace",
```
which is the default font setting.

I am on windows 10 1803. Are you on the latest version of windows?

**Comment by czhang03** [comment]
I think I may have some fallback font installed that is perventing me to reproduce this issue. (or maybe you have some fallback font that is changed?)

Can you suggest a way for me to find out my fallback font?

**Pull request merged**
